// js/data.js - 50 Örnek Usta Verisi (Tüm telefonlar: 0506 027 05 51)
const ustalarDB = [
  // TEMİZLİK (10 kişi)
  {
    id: 1,
    adSoyad: "Ayşe Yılmaz",
    kategori: "temizlik",
    altKategori: "Ev Temizliği",
    puan: 4.8,
    degerlendirmeSayisi: 127,
    konum: "Giresun Merkez",
    mahalle: "Kale",
    uzaklik: 1.2,
    deneyim: 8,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=5",
    aciklama: "8 yıllık deneyimli ev temizliği uzmanı. Detaycı ve güvenilir.",
    fiyatAraligi: "150-250 TL/saat",
    calismaSaatleri: "08:00-18:00",
    sertifikalar: ["Sağlık Sertifikası", "Temizlik Eğitimi"],
    yorumlar: ["Çok titiz çalışıyor", "Güvenilir", "Tavsiye ederim"]
  },
  {
    id: 2,
    adSoyad: "Fatma Kaya",
    kategori: "temizlik",
    altKategori: "Ofis Temizliği",
    puan: 4.9,
    degerlendirmeSayisi: 89,
    konum: "Giresun Merkez",
    mahalle: "Çınarlar",
    uzaklik: 2.5,
    deneyim: 12,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=9",
    aciklama: "Kurumsal ofis temizliği uzmanı. Gece çalışabilir.",
    fiyatAraligi: "200-350 TL/saat",
    calismaSaatleri: "18:00-24:00",
    sertifikalar: ["OSGB Belgeli"],
    yorumlar: ["Profesyonel", "Hızlı"]
  },
  {
    id: 3,
    adSoyad: "Emine Şahin",
    kategori: "temizlik",
    altKategori: "İnşaat Sonrası",
    puan: 4.7,
    degerlendirmeSayisi: 45,
    konum: "Bulancak",
    mahalle: "Merkez",
    uzaklik: 15.0,
    deneyim: 5,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=10",
    aciklama: "İnşaat sonrası detaylı temizlik. Endüstriyel ekipman.",
    fiyatAraligi: "500-800 TL/gün",
    calismaSaatleri: "07:00-19:00",
    sertifikalar: ["Endüstriyel Temizlik"],
    yorumlar: ["Harika sonuç", "Titiz"]
  },
  {
    id: 4,
    adSoyad: "Zeynep Demir",
    kategori: "temizlik",
    altKategori: "Cam Silme",
    puan: 4.6,
    degerlendirmeSayisi: 67,
    konum: "Espiye",
    mahalle: "Sahil",
    uzaklik: 28.0,
    deneyim: 6,
    musait: false,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=20",
    aciklama: "Dış cephe ve iç mekan cam temizliği uzmanı.",
    fiyatAraligi: "100-200 TL/pencere",
    calismaSaatleri: "09:00-17:00",
    sertifikalar: ["Yüksekte Çalışma"],
    yorumlar: ["Temiz işçilik"]
  },
  {
    id: 5,
    adSoyad: "Merve Aydın",
    kategori: "temizlik",
    altKategori: "Halı Yıkama",
    puan: 4.9,
    degerlendirmeSayisi: 203,
    konum: "Tirebolu",
    mahalle: "Merkez",
    uzaklik: 45.0,
    deneyim: 10,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=24",
    aciklama: "Evde halı yıkama hizmeti. Kuru temizleme.",
    fiyatAraligi: "50-100 TL/m²",
    calismaSaatleri: "08:00-20:00",
    sertifikalar: ["Koltuk/Halı Temizlik"],
    yorumlar: ["Çok iyi", "Taze kokulu"]
  },
  {
    id: 6,
    adSoyad: "Selen Yıldız",
    kategori: "temizlik",
    altKategori: "Ev Temizliği",
    puan: 4.5,
    degerlendirmeSayisi: 34,
    konum: "Giresun Merkez",
    mahalle: "Atatürk",
    uzaklik: 3.1,
    deneyim: 3,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=16",
    aciklama: "Genç ve dinamik temizlik personeli.",
    fiyatAraligi: "120-200 TL/saat",
    calismaSaatleri: "10:00-16:00",
    sertifikalar: [],
    yorumlar: ["Güleryüzlü"]
  },
  {
    id: 7,
    adSoyad: "Buse Çelik",
    kategori: "temizlik",
    altKategori: "Ofis Temizliği",
    puan: 4.8,
    degerlendirmeSayisi: 78,
    konum: "Görele",
    mahalle: "Merkez",
    uzaklik: 38.0,
    deneyim: 7,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=32",
    aciklama: "Ofis ve mağaza temizliği uzmanı.",
    fiyatAraligi: "180-300 TL/saat",
    calismaSaatleri: "19:00-23:00",
    sertifikalar: ["İş Güvenliği"],
    yorumlar: ["Düzenli", "İyi"]
  },
  {
    id: 8,
    adSoyad: "Cansu Koç",
    kategori: "temizlik",
    altKategori: "Ev Temizliği",
    puan: 4.7,
    degerlendirmeSayisi: 56,
    konum: "Keşap",
    mahalle: "Sahil",
    uzaklik: 22.0,
    deneyim: 4,
    musait: false,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=44",
    aciklama: "Haftalık/dönemsel ev temizliği.",
    fiyatAraligi: "140-220 TL/saat",
    calismaSaatleri: "09:00-15:00",
    sertifikalar: [],
    yorumlar: ["İyi"]
  },
  {
    id: 9,
    adSoyad: "Derya Usta",
    kategori: "temizlik",
    altKategori: "İnşaat Sonrası",
    puan: 4.9,
    degerlendirmeSayisi: 112,
    konum: "Giresun Merkez",
    mahalle: "Hacısıyıvaz",
    uzaklik: 1.8,
    deneyim: 15,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=48",
    aciklama: "15 yıllık deneyim. Tadilat sonrası temizlikte uzman.",
    fiyatAraligi: "600-1000 TL/gün",
    calismaSaatleri: "07:00-19:00",
    sertifikalar: ["Uzman Temizlik"],
    yorumlar: ["Profesyonel", "Hızlı"]
  },
  {
    id: 10,
    adSoyad: "Elif Yılmaz",
    kategori: "temizlik",
    altKategori: "Cam Silme",
    puan: 4.6,
    degerlendirmeSayisi: 23,
    konum: "Bulancak",
    mahalle: "Kavaklı",
    uzaklik: 16.0,
    deneyim: 2,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=52",
    aciklama: "Cam ve vitrin temizliği.",
    fiyatAraligi: "80-150 TL/pencere",
    calismaSaatleri: "10:00-16:00",
    sertifikalar: [],
    yorumlar: ["İyi"]
  },

  // ELEKTRİK (10 kişi)
  {
    id: 11,
    adSoyad: "Mehmet Usta",
    kategori: "elektrik",
    altKategori: "Ev Elektriği",
    puan: 4.9,
    degerlendirmeSayisi: 245,
    konum: "Giresun Merkez",
    mahalle: "Kale",
    uzaklik: 0.5,
    deneyim: 20,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=11",
    aciklama: "20 yıllık elektrik ustası. Avize montaj, tadilat işleri.",
    fiyatAraligi: "200-400 TL/saat",
    calismaSaatleri: "08:00-22:00",
    sertifikalar: ["Elektrik Ustalık", "Sıcak İşletme"],
    yorumlar: ["Hızlı geldi", "İşi bilir", "Güvenilir"]
  },
  {
    id: 12,
    adSoyad: "Ali Kaya",
    kategori: "elektrik",
    altKategori: "Arıza",
    puan: 4.8,
    degerlendirmeSayisi: 189,
    konum: "Giresun Merkez",
    mahalle: "Çınarlar",
    uzaklik: 1.5,
    deneyim: 15,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=12",
    aciklama: "Elektrik arıza uzmanı. Sigorta, priz, anahtar değişimi.",
    fiyatAraligi: "150-300 TL/saat",
    calismaSaatleri: "07:00-23:00",
    sertifikalar: ["Elektrik Ustalık"],
    yorumlar: ["Acil geldi", "Çözüm odaklı"]
  },
  {
    id: 13,
    adSoyad: "Hasan Demir",
    kategori: "elektrik",
    altKategori: "Tesisat",
    puan: 4.7,
    degerlendirmeSayisi: 134,
    konum: "Espiye",
    mahalle: "Merkez",
    uzaklik: 30.0,
    deneyim: 18,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=13",
    aciklama: "Komple ev elektrik tesisatı çekimi. Topraklama.",
    fiyatAraligi: "500-1500 TL/gün",
    calismaSaatleri: "08:00-18:00",
    sertifikalar: ["Tesisat Ustalık", "Enerji Bakanlığı"],
    yorumlar: ["Profesyonel", "Temiz iş"]
  },
  {
    id: 14,
    adSoyad: "İbrahim Şahin",
    kategori: "elektrik",
    altKategori: "Klima",
    puan: 4.9,
    degerlendirmeSayisi: 167,
    konum: "Tirebolu",
    mahalle: "Sahil",
    uzaklik: 48.0,
    deneyim: 12,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=14",
    aciklama: "Klima montaj, demontaj, bakım. Inverter uzmanı.",
    fiyatAraligi: "400-800 TL/adet",
    calismaSaatleri: "09:00-19:00",
    sertifikalar: ["Klima Teknik Servis"],
    yorumlar: ["Klima sorununu çözdü", "İyi"]
  },
  {
    id: 15,
    adSoyad: "Osman Aydın",
    kategori: "elektrik",
    altKategori: "Ev Elektriği",
    puan: 4.6,
    degerlendirmeSayisi: 98,
    konum: "Bulancak",
    mahalle: "Merkez",
    uzaklik: 14.0,
    deneyim: 10,
    musait: false,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=15",
    aciklama: "Ev içi elektrik işleri. Led aydınlatma.",
    fiyatAraligi: "180-350 TL/saat",
    calismaSaatleri: "10:00-18:00",
    sertifikalar: ["Elektrik Ustalık"],
    yorumlar: ["İyi", "Düzgün"]
  },
  {
    id: 16,
    adSoyad: "Ramazan Yıldız",
    kategori: "elektrik",
    altKategori: "Arıza",
    puan: 4.8,
    degerlendirmeSayisi: 156,
    konum: "Giresun Merkez",
    mahalle: "Atatürk",
    uzaklik: 2.8,
    deneyim: 22,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=60",
    aciklama: "Gece arıza servisi. 7/24 acil elektrik.",
    fiyatAraligi: "300-600 TL (gece tarifesi)",
    calismaSaatleri: "00:00-23:59",
    sertifikalar: ["Acil Müdahale"],
    yorumlar: ["Gece geldi", "Kurtarıcı"]
  },
  {
    id: 17,
    adSoyad: "Mustafa Çelik",
    kategori: "elektrik",
    altKategori: "Tesisat",
    puan: 4.7,
    degerlendirmeSayisi: 87,
    konum: "Görele",
    mahalle: "Merkez",
    uzaklik: 40.0,
    deneyim: 14,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=33",
    aciklama: "Endüstriyel tesisat. İşyeri elektrik projesi.",
    fiyatAraligi: "800-2000 TL/gün",
    calismaSaatleri: "08:00-17:00",
    sertifikalar: ["Proje Uzmanı"],
    yorumlar: ["İşyerimizi yaptı", "Mükemmel"]
  },
  {
    id: 18,
    adSoyad: "Hüseyin Koç",
    kategori: "elektrik",
    altKategori: "Klima",
    puan: 4.5,
    degerlendirmeSayisi: 45,
    konum: "Keşap",
    mahalle: "Sahil",
    uzaklik: 25.0,
    deneyim: 8,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=59",
    aciklama: "Klima bakım ve onarım. Gaz dolumu.",
    fiyatAraligi: "300-600 TL",
    calismaSaatleri: "09:00-18:00",
    sertifikalar: ["Klima Sertifika"],
    yorumlar: ["Soğuttu", "İyi"]
  },
  {
    id: 19,
    adSoyad: "Kemal Usta",
    kategori: "elektrik",
    altKategori: "Ev Elektriği",
    puan: 4.9,
    degerlendirmeSayisi: 234,
    konum: "Giresun Merkez",
    mahalle: "Hacısıyıvaz",
    uzaklik: 1.2,
    deneyim: 25,
    musait: false,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=68",
    aciklama: "25 yıllık usta. Eski ev tesisatı yenileme uzmanı.",
    fiyatAraligi: "250-500 TL/saat",
    calismaSaatleri: "08:00-20:00",
    sertifikalar: ["Ustalık Belgesi"],
    yorumlar: ["Usta işi", "Deneyimli"]
  },
  {
    id: 20,
    adSoyad: "Yusuf Demirtaş",
    kategori: "elektrik",
    altKategori: "Arıza",
    puan: 4.6,
    degerlendirmeSayisi: 67,
    konum: "Yağlıdere",
    mahalle: "Merkez",
    uzaklik: 55.0,
    deneyim: 6,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=53",
    aciklama: "Genç ve teknolojik elektrikçi. Akıllı ev sistemleri.",
    fiyatAraligi: "200-400 TL/saat",
    calismaSaatleri: "10:00-19:00",
    sertifikalar: ["Akıllı Ev Sistemleri"],
    yorumlar: ["Modern", "Bilgili"]
  },

  // NAKLİYE (5 kişi)
  {
    id: 21,
    adSoyad: "Ahmet Nakliyeci",
    kategori: "nakliye",
    altKategori: "Ev Taşıma",
    puan: 4.8,
    degerlendirmeSayisi: 178,
    konum: "Giresun Merkez",
    mahalle: "Sanayi",
    uzaklik: 3.0,
    deneyim: 15,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=11",
    aciklama: "15 yıllık nakliyeci. Sigortalı taşıma. Asansörlü araç.",
    fiyatAraligi: "1000-5000 TL",
    calismaSaatleri: "07:00-22:00",
    sertifikalar: ["SRC Belgesi", "Sigortalı Nakliye"],
    yorumlar: ["Dikkatli", "Hızlı", "Eşyalar sağlam"]
  },
  {
    id: 22,
    adSoyad: "Mehmet Kamyoncu",
    kategori: "nakliye",
    altKategori: "Ofis Taşıma",
    puan: 4.9,
    degerlendirmeSayisi: 134,
    konum: "Bulancak",
    mahalle: "Sanayi",
    uzaklik: 16.0,
    deneyim: 20,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=13",
    aciklama: "Kurumsal taşımacılık. Dosya ve arşiv taşıma uzmanı.",
    fiyatAraligi: "2000-10000 TL",
    calismaSaatleri: "08:00-18:00",
    sertifikalar: ["K3 Yetki Belgesi"],
    yorumlar: ["Profesyonel", "Düzenli"]
  },
  {
    id: 23,
    adSoyad: "İsmail Taşımacı",
    kategori: "nakliye",
    altKategori: "Parça Eşya",
    puan: 4.7,
    degerlendirmeSayisi: 89,
    konum: "Espiye",
    mahalle: "Merkez",
    uzaklik: 32.0,
    deneyim: 10,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=17",
    aciklama: "Kamyonet ile parça eşya taşıma. Sehir içi/dışı.",
    fiyatAraligi: "200-1000 TL",
    calismaSaatleri: "08:00-20:00",
    sertifikalar: ["Ehliyet C"],
    yorumlar: ["Ekonomik", "Hızlı"]
  },
  {
    id: 24,
    adSoyad: "Hakan Nakliyat",
    kategori: "nakliye",
    altKategori: "Ev Taşıma",
    puan: 4.6,
    degerlendirmeSayisi: 56,
    konum: "Tirebolu",
    mahalle: "Merkez",
    uzaklik: 50.0,
    deneyim: 8,
    musait: false,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=19",
    aciklama: "Tirebolu bölgesi nakliye. Eşya paketleme.",
    fiyatAraligi: "800-4000 TL",
    calismaSaatleri: "09:00-19:00",
    sertifikalar: [],
    yorumlar: ["İyi"]
  },
  {
    id: 25,
    adSoyad: "Burak Taşımacılık",
    kategori: "nakliye",
    altKategori: "Ofis Taşıma",
    puan: 4.8,
    degerlendirmeSayisi: 112,
    konum: "Giresun Merkez",
    mahalle: "Organize Sanayi",
    uzaklik: 5.0,
    deneyim: 12,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=21",
    aciklama: "Asansörlü nakliye. 12 kat çıkabilir.",
    fiyatAraligi: "1500-8000 TL",
    calismaSaatleri: "07:00-21:00",
    sertifikalar: ["Asansörlü Araç"],
    yorumlar: ["Asansör harika", "Zamanında"]
  },

  // BOYA (10 kişi)
  {
    id: 26,
    adSoyad: "Recep Boyacı",
    kategori: "boya",
    altKategori: "İç Cephe",
    puan: 4.9,
    degerlendirmeSayisi: 267,
    konum: "Giresun Merkez",
    mahalle: "Kale",
    uzaklik: 1.0,
    deneyim: 22,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=12",
    aciklama: "22 yıllık boya ustası. Hazır sıva ve badana uzmanı.",
    fiyatAraligi: "150-300 TL/m²",
    calismaSaatleri: "08:00-18:00",
    sertifikalar: ["Boya Ustalık"],
    yorumlar: ["Titiz", "Rengi iyi tutturdu", "Temiz çalıştı"]
  },
  {
    id: 27,
    adSoyad: "Mahmut Badanacı",
    kategori: "boya",
    altKategori: "Dış Cephe",
    puan: 4.8,
    degerlendirmeSayisi: 189,
    konum: "Giresun Merkez",
    mahalle: "Çınarlar",
    uzaklik: 2.0,
    deneyim: 18,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=14",
    aciklama: "Dış cephe mantolama ve boya. İskele kurulumu.",
    fiyatAraligi: "200-400 TL/m²",
    calismaSaatleri: "07:00-17:00",
    sertifikalar: ["İskele Kurulum", "Yüksekte Çalışma"],
    yorumlar: ["Dayanıklı boya", "Profesyonel"]
  },
  {
    id: 28,
    adSoyad: "Ali Dekor",
    kategori: "boya",
    altKategori: "Dekoratif",
    puan: 4.9,
    degerlendirmeSayisi: 145,
    konum: "Bulancak",
    mahalle: "Merkez",
    uzaklik: 15.0,
    deneyim: 15,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=16",
    aciklama: "Dekoratif boya. Efekt boya, desenli badana.",
    fiyatAraligi: "300-600 TL/m²",
    calismaSaatleri: "09:00-18:00",
    sertifikalar: ["Dekorasyon Uzmanı"],
    yorumlar: ["Sanat gibi", "Harika desenler"]
  },
  {
    id: 29,
    adSoyad: "Veli Renkli",
    kategori: "boya",
    altKategori: "İç Cephe",
    puan: 4.7,
    degerlendirmeSayisi: 98,
    konum: "Espiye",
    mahalle: "Sahil",
    uzaklik: 30.0,
    deneyim: 12,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=18",
    aciklama: "İç mekan boya. Hazır sıva uygulama.",
    fiyatAraligi: "120-250 TL/m²",
    calismaSaatleri: "08:00-17:00",
    sertifikalar: [],
    yorumlar: ["İyi", "Hızlı"]
  },
  {
    id: 30,
    adSoyad: "Kazım Dışcephe",
    kategori: "boya",
    altKategori: "Dış Cephe",
    puan: 4.8,
    degerlendirmeSayisi: 167,
    konum: "Tirebolu",
    mahalle: "Merkez",
    uzaklik: 48.0,
    deneyim: 20,
    musait: false,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=20",
    aciklama: "Apartman boyacısı. Site ve bina dış cephe.",
    fiyatAraligi: "180-350 TL/m²",
    calismaSaatleri: "07:00-16:00",
    sertifikalar: ["Bina Boyacılığı"],
    yorumlar: ["Düzenli", "Kaliteli"]
  },
  {
    id: 31,
    adSoyad: "Selçuk Boya",
    kategori: "boya",
    altKategori: "Dekoratif",
    puan: 4.6,
    degerlendirmeSayisi: 76,
    konum: "Görele",
    mahalle: "Merkez",
    uzaklik: 42.0,
    deneyim: 10,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=22",
    aciklama: "İtalyan boya teknikleri. Alçıpan boya.",
    fiyatAraligi: "250-500 TL/m²",
    calismaSaatleri: "09:00-18:00",
    sertifikalar: ["İtalyan Dekorasyon"],
    yorumlar: ["Şık", "İyi"]
  },
  {
    id: 32,
    adSoyad: "Cemal İçboya",
    kategori: "boya",
    altKategori: "İç Cephe",
    puan: 4.7,
    degerlendirmeSayisi: 134,
    konum: "Keşap",
    mahalle: "Sahil",
    uzaklik: 24.0,
    deneyim: 14,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=24",
    aciklama: "Keşap bölgesi boyacı. Hızlı ve temiz.",
    fiyatAraligi: "140-280 TL/m²",
    calismaSaatleri: "08:00-19:00",
    sertifikalar: [],
    yorumlar: ["Temiz", "Hızlı"]
  },
  {
    id: 33,
    adSoyad: "Yakup Badana",
    kategori: "boya",
    altKategori: "Dış Cephe",
    puan: 4.5,
    degerlendirmeSayisi: 45,
    konum: "Giresun Merkez",
    mahalle: "Atatürk",
    uzaklik: 3.5,
    deneyim: 8,
    musait: false,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=26",
    aciklama: "Genç boyacı. Uygun fiyat.",
    fiyatAraligi: "100-200 TL/m²",
    calismaSaatleri: "10:00-18:00",
    sertifikalar: [],
    yorumlar: ["Ekonomik"]
  },
  {
    id: 34,
    adSoyad: "Tekin Dekorasyon",
    kategori: "boya",
    altKategori: "Dekoratif",
    puan: 4.9,
    degerlendirmeSayisi: 198,
    konum: "Giresun Merkez",
    mahalle: "Hacısıyıvaz",
    uzaklik: 2.2,
    deneyim: 25,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=28",
    aciklama: "25 yıllık dekorasyon ustası. Lüks konut uzmanı.",
    fiyatAraligi: "400-800 TL/m²",
    calismaSaatleri: "09:00-17:00",
    sertifikalar: ["Usta Öğretici"],
    yorumlar: ["Elite hizmet", "Mükemmel"]
  },
  {
    id: 35,
    adSoyad: "Ferhat Boyacı",
    kategori: "boya",
    altKategori: "İç Cephe",
    puan: 4.6,
    degerlendirmeSayisi: 67,
    konum: "Yağlıdere",
    mahalle: "Merkez",
    uzaklik: 58.0,
    deneyim: 9,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=30",
    aciklama: "Yağlıdere ve çevresi. Köy evleri boyama.",
    fiyatAraligi: "80-180 TL/m²",
    calismaSaatleri: "08:00-17:00",
    sertifikalar: [],
    yorumlar: ["İyi"]
  },

  // MARANGOZ (5 kişi)
  {
    id: 36,
    adSoyad: "Hüseyin Marangoz",
    kategori: "marangoz",
    altKategori: "Mobilya",
    puan: 4.9,
    degerlendirmeSayisi: 234,
    konum: "Giresun Merkez",
    mahalle: "Sanayi",
    uzaklik: 4.0,
    deneyim: 30,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=13",
    aciklama: "30 yıllık kalfa. Klasik mobilya restorasyonu.",
    fiyatAraligi: "300-1000 TL/saat",
    calismaSaatleri: "08:00-18:00",
    sertifikalar: ["Usta Öğretici", "Ahşap Ustalık"],
    yorumlar: ["Sanatkar", "Kaliteli iş", "Eski mobilyayı yeniledi"]
  },
  {
    id: 37,
    adSoyad: "Salim Doğramacı",
    kategori: "marangoz",
    altKategori: "Kapı/Pencere",
    puan: 4.8,
    degerlendirmeSayisi: 178,
    konum: "Bulancak",
    mahalle: "Sanayi",
    uzaklik: 17.0,
    deneyim: 20,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=15",
    aciklama: "PVC ve ahşap doğrama. Sineklik imalatı.",
    fiyatAraligi: "500-2000 TL/adet",
    calismaSaatleri: "08:00-19:00",
    sertifikalar: ["PVC Ustalık"],
    yorumlar: ["İyi ölçü aldı", "Sıkı işçilik"]
  },
  {
    id: 38,
    adSoyad: "Nuri Mobilya",
    kategori: "marangoz",
    altKategori: "Mutfak Dolabı",
    puan: 4.7,
    degerlendirmeSayisi: 145,
    konum: "Espiye",
    mahalle: "Merkez",
    uzaklik: 33.0,
    deneyim: 15,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=17",
    aciklama: "Mutfak ve banyo dolabı. Lake boya uzmanı.",
    fiyatAraligi: "2000-10000 TL/proje",
    calismaSaatleri: "09:00-18:00",
    sertifikalar: ["Mutfak Uzmanı"],
    yorumlar: ["Modern tasarım", "Fonksiyonel"]
  },
  {
    id: 39,
    adSoyad: "Ramazan Ahşap",
    kategori: "marangoz",
    altKategori: "Parke",
    puan: 4.8,
    degerlendirmeSayisi: 123,
    konum: "Tirebolu",
    mahalle: "Merkez",
    uzaklik: 52.0,
    deneyim: 18,
    musait: false,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=19",
    aciklama: "Parke döşeme ve cilalama. Lamine parke uzmanı.",
    fiyatAraligi: "50-150 TL/m²",
    calismaSaatleri: "08:00-17:00",
    sertifikalar: ["Parke Ustalık"],
    yorumlar: ["Düzgün döşedi", "Temiz"]
  },
  {
    id: 40,
    adSoyad: "Furkan Kereste",
    kategori: "marangoz",
    altKategori: "Mobilya",
    puan: 4.6,
    degerlendirmeSayisi: 89,
    konum: "Giresun Merkez",
    mahalle: "Atatürk",
    uzaklik: 3.0,
    deneyim: 10,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=21",
    aciklama: "Genç marangoz. Modern tasarım. İkea montaj.",
    fiyatAraligi: "200-600 TL/saat",
    calismaSaatleri: "10:00-20:00",
    sertifikalar: [],
    yorumlar: ["Hızlı", "Modern"]
  },

  // TESİSAT (10 kişi)
  {
    id: 41,
    adSoyad: "Mustafa Tesisatçı",
    kategori: "tesisat",
    altKategori: "Su Tesisatı",
    puan: 4.9,
    degerlendirmeSayisi: 312,
    konum: "Giresun Merkez",
    mahalle: "Kale",
    uzaklik: 0.8,
    deneyim: 25,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=14",
    aciklama: "25 yıllık tesisat ustası. Kaçak tespiti cihazlı.",
    fiyatAraligi: "200-500 TL/saat",
    calismaSaatleri: "07:00-23:00",
    sertifikalar: ["Tesisat Ustalık", "Sıhhi Tesisat"],
    yorumlar: ["Kaçağı buldu", "Hızlı", "Temiz"]
  },
  {
    id: 42,
    adSoyad: "İbrahim Sıhhi",
    kategori: "tesisat",
    altKategori: "Kanalizasyon",
    puan: 4.8,
    degerlendirmeSayisi: 267,
    konum: "Giresun Merkez",
    mahalle: "Çınarlar",
    uzaklik: 1.8,
    deneyim: 22,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=16",
    aciklama: "Robotlu tıkanıklık açma. Kanal görüntüleme.",
    fiyatAraligi: "300-800 TL",
    calismaSaatleri: "00:00-23:59",
    sertifikalar: ["Kanal Görüntüleme"],
    yorumlar: ["Açtı", "Kokusuz", "Teknolojik"]
  },
  {
    id: 43,
    adSoyad: "Osman Musluk",
    kategori: "tesisat",
    altKategori: "Batarya Değişim",
    puan: 4.7,
    degerlendirmeSayisi: 198,
    konum: "Bulancak",
    mahalle: "Merkez",
    uzaklik: 15.0,
    deneyim: 18,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=18",
    aciklama: "Batarya, rezervuar, klozet değişimi. Seramik tamir.",
    fiyatAraligi: "150-400 TL/adet",
    calismaSaatleri: "08:00-19:00",
    sertifikalar: ["Sıhhi Tesisat"],
    yorumlar: ["Hızlı", "Düzgün"]
  },
  {
    id: 44,
    adSoyad: "Kemal Kaçak",
    kategori: "tesisat",
    altKategori: "Su Kaçağı",
    puan: 4.9,
    degerlendirmeSayisi: 289,
    konum: "Espiye",
    mahalle: "Sahil",
    uzaklik: 31.0,
    deneyim: 20,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=20",
    aciklama: "Termal kamera ile kaçak tespiti. Kırmadan tamir.",
    fiyatAraligi: "400-1000 TL",
    calismaSaatleri: "08:00-22:00",
    sertifikalar: ["Termal Kamera", "Kırmadan Tespit"],
    yorumlar: ["Duvarı kırmadı", "Buldu kaçağı", "Harika"]
  },
  {
    id: 45,
    adSoyad: "Yusuf Kombi",
    kategori: "tesisat",
    altKategori: "Kombi/Petek",
    puan: 4.8,
    degerlendirmeSayisi: 234,
    konum: "Tirebolu",
    mahalle: "Merkez",
    uzaklik: 49.0,
    deneyim: 16,
    musait: false,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=22",
    aciklama: "Kombi bakım ve onarım. Petek temizliği.",
    fiyatAraligi: "300-800 TL",
    calismaSaatleri: "09:00-18:00",
    sertifikalar: ["Kombi Teknik Servis"],
    yorumlar: ["Isıttı", "Bakımlı"]
  },
  {
    id: 46,
    adSoyad: "Hakan Gider",
    kategori: "tesisat",
    altKategori: "Su Tesisatı",
    puan: 4.6,
    degerlendirmeSayisi: 134,
    konum: "Görele",
    mahalle: "Merkez",
    uzaklik: 41.0,
    deneyim: 12,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=24",
    aciklama: "Görele bölgesi tesisat. Yeni yapı tesisatı çekimi.",
    fiyatAraligi: "250-600 TL/saat",
    calismaSaatleri: "08:00-17:00",
    sertifikalar: [],
    yorumlar: ["İyi"]
  },
  {
    id: 47,
    adSoyad: "Burak Tıkanıklık",
    kategori: "tesisat",
    altKategori: "Kanalizasyon",
    puan: 4.7,
    degerlendirmeSayisi: 167,
    konum: "Keşap",
    mahalle: "Sahil",
    uzaklik: 26.0,
    deneyim: 14,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=26",
    aciklama: "Acil tıkanıklık açma. Lavabo, tuvalet, gider.",
    fiyatAraligi: "200-500 TL",
    calismaSaatleri: "07:00-24:00",
    sertifikalar: ["Acil Tesisat"],
    yorumlar: ["Hemen geldi", "Açtı"]
  },
  {
    id: 48,
    adSoyad: "Serkan Su",
    kategori: "tesisat",
    altKategori: "Batarya Değişim",
    puan: 4.5,
    degerlendirmeSayisi: 98,
    konum: "Giresun Merkez",
    mahalle: "Atatürk",
    uzaklik: 2.5,
    deneyim: 8,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=28",
    aciklama: "Genç tesisatçı. Uygun fiyatlı batarya değişimi.",
    fiyatAraligi: "100-300 TL",
    calismaSaatleri: "10:00-19:00",
    sertifikalar: [],
    yorumlar: ["Ekonomik"]
  },
  {
    id: 49,
    adSoyad: "Murat Petek",
    kategori: "tesisat",
    altKategori: "Kombi/Petek",
    puan: 4.8,
    degerlendirmeSayisi: 156,
    konum: "Giresun Merkez",
    mahalle: "Hacısıyıvaz",
    uzaklik: 1.5,
    deneyim: 19,
    musait: true,
    acil: true,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=30",
    aciklama: "Petek temizliği ve kombi bakım uzmanı. Kimyasal temizlik.",
    fiyatAraligi: "250-700 TL",
    calismaSaatleri: "08:00-20:00",
    sertifikalar: ["Petek Temizlik"],
    yorumlar: ["Sıcak geldi", "Verimli"]
  },
  {
    id: 50,
    adSoyad: "Ufuk Tesisat",
    kategori: "tesisat",
    altKategori: "Su Kaçağı",
    puan: 4.6,
    degerlendirmeSayisi: 112,
    konum: "Yağlıdere",
    mahalle: "Merkez",
    uzaklik: 60.0,
    deneyim: 11,
    musait: true,
    acil: false,
    telefon: "0506 027 05 51",
    foto: "https://i.pravatar.cc/150?img=32",
    aciklama: "Yağlıdere ve çevre köyler. Tesisat tamiratı.",
    fiyatAraligi: "200-600 TL",
    calismaSaatleri: "09:00-17:00",
    sertifikalar: [],
    yorumlar: ["Köye geldi", "Sağlam"]
  }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ustalarDB;
}